project:
  type: website

website:
  title: "A blog with no name"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/hughesan
      - icon: cloud-lightning-rain
        href: https://alxhug.bsky.social/
      - icon: strava
        href: https://www.strava.com/athletes/alxhug
format:
  html:
    theme: united
    css: styles.css



