project:
  type: website
  output-dir: docs

website:
  google-analytics: "G-NWH73BF1QN"
  title: "Cauchy's Lap: a running blog"
  navbar:
    search: true
    logo: "inkscape-logo/bitmap2.png"
    right:
      - text: "Blog"
        file: blog.qmd
      - text: "Connect with Me"
        menu:
          - text: "My CV"
            href: Hughes_CV_2025.pdf
          - text: "LinkedIn"
            href: "https://www.linkedin.com/in/alexandria-hughes-phd"
          - text: "Strava"
            href: https://www.strava.com/athletes/alxhug
          - text: "Bluesky"
            href: https://alxhug.bsky.social/
  page-footer:
    left: |
      © 2025 Alexandria N. Hughes
      [![CC BY-NC-SA 4.0](https://licensebuttons.net/l/by-nc-sa/4.0/88x31.png)](https://creativecommons.org/licenses/by-nc-sa/4.0/)
      <br>
      This work is licensed under a
      [Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-nc-sa/4.0/).

format:
  html:
    theme: 
      - united
      - styles-mod.scss
      



