project:
  type: website
  output-dir: docs

website:
  title: "Cauchy's Lap"
  navbar:
    search: true
    logo: "inkscape-logo/bitmap2.png"
    right:
      - text: "About"
        file: about.qmd
      - text: "Connect with Me"
        menu:
          - text: "My CV"
            href: Hughes_CV_2025.pdf
          - text: "LinkedIn"
            href: "https://www.linkedin.com/in/alexandria-hughes-phd"
          - text: "Strava"
            href: https://www.strava.com/athletes/alxhug
          - text: "Bluesky"
            href: https://alxhug.bsky.social/

format:
  html:
    theme: 
      - united
      - styles-mod.scss
      



