---
title: "About me"
description: |
  Hi there! I'm Alex.
  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

I'm a neuroscientist currently living in Denver, Colorado, and relocating to the DC area soon to pursue postdoctoral training at the NIH. I grew up in Corvallis, Oregon, and Boise, Idaho, and came to Denver to pursue a PhD in Neuroscience at the University of Colorado, Anschutz Medical Campus. My research is described on my [Research](research.html) page. My career goal is to become an independent investigator in neuroscience and to teach statistics courses for researchers in the biological sciences (Why? Check out [this](https://doi.org/10.1038/nn.2886) and  [this](https://doi.org/10.1523/ENEURO.0030-16.2016)).

During my undergraduate education I studied math and biology and worked full-time tutoring, TAing, and teaching math courses for 3 years. I'm passionate about math education and dismantling the idea that math isn't for everyone. I realized after graduating that I want to make this part of my career. So, in addition to being a postdoc in Neuroscience, I'm slowly chipping away at an MS in Statistics so that I can make math and stats education for biologists part of my academic career. 

Outside of the lab and classroom, I'm an avid [distance runner](misc.html), [cat mom](cauchy.html), [amateur artist](page.html), and board game enthusiast. And, unlike this paragraph, I don't compartmentalize or make any real attempt to separate these parts of my life from the science part. I built this website with the R package {Distill}, which you can learn more about [here](https://rstudio.github.io/distill/).