---
title: "Training plan for the 2025 Boston Marathon"
author: "Alex Hughes"
date: "2024-12-17"
date-modified: "2024-12-20"
categories: [running]
---

I'm 18 weeks out from the 2025 Boston Marathon! Boston will be my third and hilliest marathon. Here's how I'm planning to train for it.

## My history with training plans

For my first marathon, the Eugene Marathon in April 2024, I used [Hal Higdon's Advanced-1 plan](https://www.halhigdon.com/training-programs/marathon-training/advanced-1-marathon). This was my first time following a training plan of any type, though I only really followed the marathon pace workouts and the long run progression, letting myself fill the rest of the week with whatever easy mileage I desired rather than the miles stipulated by HH. I also included one weekly threshold run that included 20 minutes at threshold. On the weeks of the 20-milers, my weekly mileage reached just over 55 miles, with most other weeks being somewhere in the 45-52 mile range.  

The race went well enough for a first time - I finished, I didn't get injured, I qualified for Boston (!) - but I felt my pace slow in the last 4 miles and I was interested in ways to overcome this. I had read about plans that combine marathon pace work with long runs and I thought this approach might help. A little searching brought me to *Advanced Marathoning* by Pfitzinger & Douglas, a book of training plans beloved by the folks over at r/AdvancedRunning.

I decided to follow a so-called "Pfitz" plan for my second marathon, which was the Richmond Marathon held in November. I chose the 18-week 55 mile plan, which peaks at 55 miles per week (mpw) but starts much lower at 33 mpw. I had been running ~40 mpw for about 7 years before I started training for Eugene, and was back to a base level of 45 mpw before training for Richmond. For the first few weeks of the plan, which were lower in mileage, I followed the plan workouts and added easy miles as needed to stay at or above my 45 mpw base until the plan's increasing weekly mileage caught up to my own.

Pfitz 18/55 was a great plan. I followed the workouts, but like my experience with HH, I didn't stringently follow the miles scheduled on easy/recovery days because (I don't really think it matters and) I like flexibility. I also didn't follow the tune-up races with long runs, simply because I keep my running week Sunday - Saturday (Pfitz plans are written Monday - Sunday) and there are no races on Fridays, at least where I live. My favorite part of the Pfitz plan was the inclusion of mid-week medium-long runs of 11-12 miles - I felt like these really helped my endurance. I questioned the weekly VO2max track work in the final weeks of the plan and often only completed 1/2 of the reps and then hit my local hill for some strides. All in all, the plan delivered and I shaved 13 minutes off of my Eugene time. The last 6 miles were among my fastest, too, which was what I was hoping to achieve with Pfitz.

## What am I going to do differently this time?

In adding easy miles to Pfitz 18/55, my peak mileage reached 65 mpw and I had 3-4 weeks around 58-62 mpw. The next step up in the Pfitz plan series are the 70 mpw peak plans (18/70 and 12/70). For Boston, I plan to follow the 18/70 plan. I didn't feel overly fatigued or ever struggle to complete workouts in the 18/55 plan, even with the additional mileage and ending most long runs with a decent chunk at marathon pace. I'm nervous to add mileage because I'm terribly afraid of injury but excited to make the leap and see how much adding volume makes a difference in my time.

Still, I can't seem to follow a plan without putting my own spin on it, so I'm going to make some modifications:

  + This plan includes doubles, but it's not high enough mileage to warrant doubles (imo) so I'm not going to do the doubles. Scheduled doubles are 6 miles am + 4 miles pm. I'll probably just run between 6-10 miles and call it good enough.
  
  + I scaled the total weekly miles down just a bit by multiplying each week by a factor of 67.5/70. So, I'll actually peak at 67.5 mpw, and several weeks will be in the 63-66 mpw range. As for where to reduce miles to achieve this, I'll reference the 18/55 plan and make sure I don't change any workouts that are conserved between the plans (e.g., the LT/threshold workouts are identical between the plans, with the 18/70 LT workouts including 1 additional non-LT easy mile). I'm likely to drop a mile from a mid-week 15 miler, or a mile or two from a recovery run.
  
## What about strength work?

For the past couple years I have been in a good groove with strength training and generally train 3x per week following shorter runs. There are different perspectives on when to schedule strength work, but a more common viewpoint is that "easy days should be easy, and hard days should be hard", i.e. do strength training after speedwork or an otherwise hard run. I'm not going to challenge this directly, but over time I have found myself favoring strength work on short days for reasons of both time management and load management.  

One of the challenges of Pfitz 18/70 vs 18/55 is the number and placement of the workout days (by which I mean anything that isn't a recovery run). Generally, 18/70 has 4-5 workout days per week, and most of these are medium-long or long runs. I generally don't have time to add 30-50 minutes of strength work after 1h30 - 2h of running. But it's also said that strength work shouldn't take place the day before speedwork or a long run, which knocks out most of the days of the week.

I'm tentatively going to continue doing strength work on recovery days, because it has worked for me this far and I'm almost never sore to a point that my running is compromised. I'll probably do a post about strength training at some point because I've come to really enjoy it.
