---
title: "Injury"
author: "Alex Hughes"
date: "2025-1-6"
date-modified: "2025-1-6"
categories: []
draft: true
---

After my first week of Pfitz 18/70, I got injured. I don't think it was the running that injured me but, you know, it probably was (or at least wore me down so that other movement was less tolerable). We were traveling for Christmas by train and due to weather delays concerned that we were going to miss our transfer. I bounded up flights of stairs in new heavy, slightly heeled boots carrying my overstuffed suitcase in one hand and at one point felt a slight shifting sensation in my left knee. There was no pain or swelling, but at the local gym treadmill the next morning I couldn't get settled into a rhythm. It felt like my leg wasn't on straight and I had a vague sore/weird/not painful sensation spanning my outer lower quad to the top of my shin. I stopped a few times in the first 10 minutes to do leg swings and bend my knee to try to get it to pop because it felt like that was what it needed to do. I managed to run a few miles with this odd sensation not letting up. At this gym, the cardio machines were upstairs. It was when I tried to go down the stairs that I realized something was horribly wrong. I had sudden, severe pain inside my knee when stepping down with my right (uninjured) leg. I otherwise had no pain, which was stressful because I didn't know what type of movements to avoid and I was afraid that I would forget to be careful and do something that would cause me pain again.

It was snowy and the gym was closed for Christmas, so I didn't run again until the morning after returning home 3 days later. This was after a few days of icing and ibuprofen and with no pain at rest or on stairs I thought I could try running again. Three minutes later, I returned home. The discomfort set in almost instantly with the impact of each stride so I looped around and went home. I booked an ortho appointment for the following week (the soonest available) - nice just to have it on the calendar, and I could cancel if I miraculously healed before then. After my very short run I had sharp pains on the stairs again like I had experienced at the gym and my knee was achy and sensitive for the rest of the day. In the week that followed I repeated this pattern a couple more times - I'd take a few days off, try running for ~5 minutes, and end up with an achy knee for 1-2 days afterward. 

When I did go to my ortho, I had taken 10 days off of real running (excluding my experimental jaunts), which was the longest I had ever taken off. I was having a good knee day on the day of my appointment, and I passed all of the knee tests for IT band syndrome (ITBS) and meniscus and ligament injuries. I went to the appointment assuming that I had ITBS


